name: flutter_skeleton
description: Flutter Skeleton

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.1.1
  provider: ^6.0.5
  easy_localization: ^3.0.1
  flutter_form_builder: ^7.8.0
  form_builder_validators: ^8.5.0
  sizer: ^2.0.15
  go_router: ^6.5.5
  shared_preferences: ^2.1.0
  pretty_dio_logger: ^1.3.1
  git_hooks: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  git_hooks: ^1.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/translations/
